### ISSUE TITLE
importance & order of rules when expanding/creating shorthands

### ISSUE THREAD

**Issue by ju1ius** [MyIntervals/PHP-CSS-Parser#29]
``` css
p {
  border-left: 1px solid rgb(0,0,0);
  border: none !important;
}
/* When run through expandShorthands and createShorthands, this becomes: */
p {
  border-left-width: 1px;
  border-left-color: rgb(0,0,0);
  border: none;
}
```
