### ISSUE TITLE
Parse Comments?

### ISSUE THREAD

**Issue by billdami** [MyIntervals/PHP-CSS-Parser#38]
Would it be possible to add the ability to parse comments that are both associated with a specific declaration block (aka are within the rule's opening and closing braces), and just global comments that are at the root document level?

For instance, for a CSS snippet like this:

``` css
h1 {
  /* my comment */
  color: #000000;
  font-size: 24px;
}
```

Would be parsed to (in simplified structure):

```
    declaration block =>
        selector =>  "h1"
        comments => array
            "my comment"
        ruleset => array
            ....
```
