### ISSUE TITLE
Duplicated semicolons generates exception in CSSParser::parseIdentifier

### ISSUE THREAD

**Issue by raffishquartan** [MyIntervals/PHP-CSS-Parser#42]
Trying to parse the DokuWiki CSS file at the link below generates an exception in CSSParser::parseIdentifier() on line 115 with the message "Identifier expected, got ;widt".

CSS file link: http://www.syntilect.com/cgf/lib/exe/css.php

Examining the CSS file shows a duplicated semicolon (after right:237px). I suspect this is affecting the parser - will have a look and see if I can find an easy fix.

``` css
div.dokuwiki div.ajax_qsearch{position:absolute;right:237px;;width:200px;opacity:0.9;display:none;font-size:80%;line-height:1.2em;border:1px solid #8cacbb;background-color:#f7f9fa;text-align:left;padding:4px;}
```
