### ISSUE TITLE
Add support for CSS Nesting

### ISSUE THREAD

**Issue by jonaskohl** [MyIntervals/PHP-CSS-Parser#524]
Current browsers support the *CSS Nesting Module* ([see spec](https://drafts.csswg.org/css-nesting/)). This package currently does not support it.

Given the input

```css
.nesting {
  color: hotpink;

  > .is {
    color: rebeccapurple;

    > .awesome {
      color: deeppink;
    }
  }
}
```

the current output is

```css
.nesting {
        color: hotpink;
        color: rebeccapurple;
        color: deeppink;
}
```

whereas it should remain unchanged or at least be transformed to something like this:

```css
.nesting {
  color: hotpink;
}

.nesting > .is {
  color: rebeccapurple;
}

.nesting > .is > .awesome {
  color: deeppink;
}
```
