### ISSUE TITLE
Error with incorrect CSS

### ISSUE THREAD

**Issue by ZhukV** [MyIntervals/PHP-CSS-Parser#70]
``` css
#home .bg-layout { background-image: url(/bundles/main/img/bg1.png?5);};
```

This css content is valid, but failed parse process (Last ";").
Thank.
