### ISSUE TITLE
Support CSS3 calc()

### ISSUE THREAD

**Issue by mikkorantalainen** [MyIntervals/PHP-CSS-Parser#79]
Following document throws `Sabberworm\CSS\Parsing\UnexpectedTokenException` with message `Identifier expected. Got “+ 20p”`. This is expected to be valid CSS document:

``` css
body
{
    border-top: solid green 0em;
    border-top-width: calc(1em + 20px);
}
```

The parser is initialized like this:

``` php
$settings = Sabberworm\CSS\Settings::create();
$settings->beStrict();
$parser = new Sabberworm\CSS\Parser($css, $settings);
```

I think `Parser::parseValue()` would need to be modified but I have no idea how to fix this.
