### ISSUE TITLE
Multiple backgrounds

### ISSUE THREAD

**Issue by celorodovalho** [MyIntervals/PHP-CSS-Parser#82]
Hi,
I have the following section/rule:

``` css
.gradient {
    background: linear-gradient(45deg,transparent 0%,transparent 74%,#cce7f5 74%,#cce7f5 80%,transparent 80%,transparent 82%,#cce7f5 82%,#cce7f5 85%,transparent 85%,transparent 89%,#cce7f5 89%,#cce7f5 91%,transparent 91%,transparent 100%) no-repeat border-box,linear-gradient(to bottom,#53bce2 0%,#53bce2 80%,#54abbe 100%) no-repeat border-box;
}
```

And I need to get the value of the rule "background", but I need get separately, for exemple:

``` php
array(
    'background-image' => array(
        'linear-gradient(45deg,transparent 0%,transparent 74%,#cce7f5 74%,#cce7f5 80%,transparent 80%,transparent 82%,#cce7f5 82%,#cce7f5 85%,transparent 85%,transparent 89%,#cce7f5 89%,#cce7f5 91%,transparent 91%,transparent 100%)',
        'linear-gradient(to bottom,#53bce2 0%,#53bce2 80%,#54abbe 100%')
    ),
    'background-repeat' => array('no-repeat','no-repeat'),
    'background-origin' => array('border-box','border-box'),
);
```

...or something like this, but I just need the get the values of "background" separately (background-image, background-repeat, background-origin).
How can I do this?
